// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh1CAJ8L_OLeYxwb-pTvQnlEsxIJ370EU',
    appId: '1:764541125070:web:5b2f7244168ad5a48e2b9f',
    messagingSenderId: '764541125070',
    projectId: 'aut0guide',
    authDomain: 'aut0guide.firebaseapp.com',
    storageBucket: 'aut0guide.appspot.com',
    measurementId: 'G-TTBF47YFBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSyCapvhEIEwSd6oQijswNar7svb3pYw',
    appId: '1:764541125070:android:47e8bd6834ed988b8e2b9f',
    messagingSenderId: '764541125070',
    projectId: 'aut0guide',
    storageBucket: 'aut0guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEBRUh4uQ8kzMEQl1Xua1dlOmmElECNus',
    appId: '1:764541125070:ios:2f182eac96ff12018e2b9f',
    messagingSenderId: '764541125070',
    projectId: 'aut0guide',
    storageBucket: 'aut0guide.appspot.com',
    iosClientId: '764541125070-8fpck5vnf0cktp5ort9g94jh73au09u0.apps.googleusercontent.com',
    iosBundleId: 'com.comma.autoguide',
  );
}
